version: '3.8'

services:
  # Vue.js フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - aisa-network

  # Spring Boot バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aisa_db
      - SPRING_DATASOURCE_USERNAME=aisa_user
      - SPRING_DATASOURCE_PASSWORD=aisa_password
    depends_on:
      - db
    networks:
      - aisa-network

  # Python Flask AI サービス
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - aisa-network

  # PostgreSQL データベース
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aisa_db
      - POSTGRES_USER=aisa_user
      - POSTGRES_PASSWORD=aisa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aisa-network

volumes:
  postgres_data:

networks:
  aisa-network:
    driver: bridge 