server:
  port: 8080

spring:
  application:
    name: aisa-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aisa_db}
    username: ${SPRING_DATASOURCE_USERNAME:aisa_user}
    password: ${SPRING_DATASOURCE_PASSWORD:aisa_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

ai:
  service:
    url: ${AI_SERVICE_URL:http://ai-service:5000}

logging:
  level:
    com.aisa: DEBUG
    org.springframework.web: DEBUG 